### ISSUE TITLE
Commands can be issued without a valid call set

### ISSUE THREAD

**Issue by dpkingston** [dpkingston/arcom-interface#30]

**Comment by KG7AUL** [comment]
I believed my call WAS SET, thus the other issue. I can close it.

**Comment by dpkingston** [comment]
Logging in is not the same as setting your call.  If you clear cookies, you
should be able to reproduce the problem.  Once the cookies are set, they
are kept for a year.

-Doug-

**Comment by KG7AUL** [comment]
I realize that. The cookie was already set, that is what I'm trying to convey.

**Comment by dpkingston** [comment]
Can you give me instructions to reproduce the problem you saw?

**Comment by KG7AUL** [comment]
I can only tell you I did the control from my secondary laptop, which was logged in (.htaccess and Cookie). Checked log in morning from desktop machine where I noticed 'null'. Has only happened the one time, so far.

**Comment by dpkingston** [comment]
This should be fixed by pull request #35
