### ISSUE TITLE
If RPC Success: fails, timer is still started, blocking a redo

### ISSUE THREAD

**Issue by KG7AUL** [dpkingston/arcom-interface#39]
Just experienced this where RCP Success log at bottom shows 'Unknown error' (or the like) but then the countdown timer is already started, blocking a redo. Seem some kind of validation/flag IF error.

**Comment by dpkingston** [comment]
Filed bug: https://github.com/dpkingston/arcom-interface/issues/40

**Comment by KG7AUL** [comment]
Perhaps sending an CR (or other and wait for ACK) as the button is clicked but before the confirmation. I had hardcoded this into my original stand-alone python script as I had noticed (similar) error, then. Just FYI.

**Comment by dpkingston** [comment]
Not sure I understand.  Please explain.  Also, check the code because I
don't think I have changed the interaction here, but I could be wrong.

**Comment by KG7AUL** [comment]
Here is my original cmdSend code.. note the .1s pauses and, more importantly, the clrBuff() [which was seen used in Arcom's WebRCP]:

def cmdSend(command):
  clrBuff()
  sleep(0.1)
  command = "1*" + command + "\r"
  print " Sending: " + command
  ser.write(command)
  sleep(0.1)
  indata = ser.readline()
  print "Received: " + indata

def clrBuff():
  indata =""
  count = 0
  while (count < 5):
    indata = ser.readline()
    count +=1

**Comment by dpkingston** [comment]
I think I tried to preserve that here:
https://github.com/dpkingston/arcom-interface/blob/master/arcom-server.py#L125

I don't have time to compare line by line now, but will later.

-Doug-

**Comment by dpkingston** [comment]
I just compared your code and mine.  I think its completely compatible.  I
have more complicated logging and the testing mode code is in there too,
but if you assume testing is false and compare the active line, its
basically the same as your code.  The delays and clrbuff are there.

-Doug-

**Comment by KG7AUL** [comment]
I believe as long as there's the CR/LF or something sent to the controller, pre-command. It's like a 9600 Hayes modem, in the old days. I didn't see the 'clrBuf' where it awaits ACK but I'll look again. After initial control at ~19:30 (from secondary computer); 10 min button failed with same unknown error. Weird.

**Comment by dpkingston** [comment]
I think this issue is addressed.  If you see this again, I am very interested in what happened and what was output on the command that started the timer.
